(defun magic-eightball (seed)
  (cond ((eq seed 1)
         (print "Probably not."))
        ((eq seed 2)
         (print "Maybe!"))
        ((eq seed 3)
         (print "You might get lucky..."))
        ((eq seed 4)
         (print "Yeah baby!"))))

(magic-eightball 1)
(magic-eightball 2)
(magic-eightball 3)
(magic-eightball 4)
